language: generic
sudo:     true

matrix:
  fast_finish: true

os:
  - linux

services:
  - docker

before_install:
  - CONTAINTER=`docker run --privileged -h canfranc -td jmbenlloch/canfranc`
  - echo $CONTAINER

script:
  - docker exec -ti $CONTAINER /home/icuser/execute_tests.sh
